# Generated by Django 4.1.3 on 2023-01-14 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 59, 18, 472273)),
        ),
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.FileField(default='1.jpg', upload_to=''),
        ),
    ]
