# Generated by Django 4.1.3 on 2023-01-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photos",
            field=models.FileField(default="1.jpg", upload_to=""),
        ),
    ]
