# Generated by Django 4.1.3 on 2022-12-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(default="", upload_to="products"),
        ),
    ]
