# Generated by Django 4.1.3 on 2022-12-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="photo",
        ),
        migrations.AddField(
            model_name="product",
            name="photos",
            field=models.FileField(default="", upload_to=""),
        ),
    ]
