# Generated by Django 4.1.3 on 2023-01-14 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_created_at_alter_product_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_bidder',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 18, 1, 48, 791057)),
        ),
    ]
