# Generated by Django 4.1.3 on 2023-01-14 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_current_bidder_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 19, 32, 8, 536200)),
        ),
    ]
