# Generated by Django 4.1.3 on 2023-01-15 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_product_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 16, 15, 29, 1, 745870)
            ),
        ),
    ]
