# Generated by Django 4.1.3 on 2023-01-15 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_product_brand_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 20, 55, 48, 624931)),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
