# Generated by Django 4.1.3 on 2023-01-15 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_product_created_at_alter_product_release_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 20, 59, 0, 900526)),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_year',
            field=models.CharField(max_length=4),
        ),
    ]
