# Generated by Django 4.1.3 on 2023-01-15 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_product_created_at_alter_product_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 21, 23, 37, 522848)),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
