# Generated by Django 4.1.3 on 2023-01-17 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_product_created_at_alter_product_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 18, 16, 11, 33, 198670)
            ),
        ),
    ]
